# Generated by Django 4.1.1 on 2022-10-02 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('create_date', models.DateField(null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold_out', 'Vendido')], default='available', max_length=10)),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_back_number', models.CharField(max_length=3)),
                ('card_expiration_date', models.DateField()),
                ('purchase_key', models.CharField(max_length=6, null=True)),
                ('question_1', models.CharField(max_length=30, null=True)),
                ('question_2', models.CharField(max_length=30, null=True)),
                ('question_3', models.CharField(max_length=30, null=True)),
                ('answer_1', models.CharField(max_length=30, null=True)),
                ('answer_2', models.CharField(max_length=30, null=True)),
                ('answer_3', models.CharField(max_length=30, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artWork_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.artwork')),
                ('purchaser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.purchaser')),
            ],
        ),
    ]
