# Generated by Django 4.1.1 on 2022-10-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_purchaser_user_id_purchaser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
