# Generated by Django 4.1.1 on 2022-09-26 07:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=12)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=2)),
                ('biography', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('card_number', models.CharField(max_length=16)),
                ('card_back_number', models.CharField(max_length=3)),
                ('card_expiration_date', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artwork',
            name='state',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservado'), ('sold_out', 'Vendido')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artWork_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.artwork')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.artist'),
        ),
    ]
