# Generated by Django 4.1.1 on 2022-09-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_purchaser_answer_1_purchaser_answer_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='commission',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
