# Generated by Django 4.1.1 on 2022-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_artist_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
